workflows:
  ios-capacitor-build:
    name: Swap Barter iOS Build
    instance_type: mac_mini_m1
    max_build_duration: 60
    environment:
      node: latest
      xcode: latest
    scripts:
      - name: Bagimliliklari Kur
        script: npm install
      - name: Web Kodlarini Derle
        script: npm run build
      - name: iOS Klasoru Olusturma Denemesi
        script: |
          npm install @capacitor/ios @capacitor/core
          npx cap add ios
          npx cap sync ios
          ls -R ios  # Klasorun olusup olusmadigini kontrol et
      - name: iOS Uygulamasini Insa Et
        script: |
          cd ios/App
          pod install
          xcodebuild build -workspace App.xcworkspace -scheme App -destination generic/platform=iOS CODE_SIGNING_ALLOWED=NO